//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMES.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMES.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ログ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DM005 {
            get {
                return ResourceManager.GetString("DM005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright © Five Motion Systems,Inc. All rights reserved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FMESCPYL {
            get {
                return ResourceManager.GetString("FMESCPYL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   想定外エラー発生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM001 {
            get {
                return ResourceManager.GetString("IDM001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM003 {
            get {
                return ResourceManager.GetString("IDM003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM004 {
            get {
                return ResourceManager.GetString("IDM004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM005 {
            get {
                return ResourceManager.GetString("IDM005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ送信無し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM006 {
            get {
                return ResourceManager.GetString("IDM006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ送信有り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM007 {
            get {
                return ResourceManager.GetString("IDM007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＯＫ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM008 {
            get {
                return ResourceManager.GetString("IDM008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM009 {
            get {
                return ResourceManager.GetString("IDM009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインＩＤ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM011 {
            get {
                return ResourceManager.GetString("IDM011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM012 {
            get {
                return ResourceManager.GetString("IDM012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM013 {
            get {
                return ResourceManager.GetString("IDM013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＱＲコードを読み取ります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM015 {
            get {
                return ResourceManager.GetString("IDM015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スキャン完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM016 {
            get {
                return ResourceManager.GetString("IDM016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM018 {
            get {
                return ResourceManager.GetString("IDM018", resourceCulture);
            }
        }
    }
}
