//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// LookFont.rc で使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_LOOKFOTYPE                  129
#define IDD_DIALOG_TEXTCTRL             130
#define IDR_TOOLBAR_FONTSELECT          131
#define IDR_MENU_RCLICK                 132
#define IDD_DIALOG_SETTING_UPDATE       139
#define IDB_BITMAP_LOOKFONT             141
#define IDI_ICON_LOOKFONT               142
#define IDI_ICON_LICENCE                145
#define IDD_DIALOG_SNKEY                146
#define IDB_SN_KEY                      147
#define IDI_ICON_CAUTION                148
#define IDD_DIALOG_UNLOCK               149
#define IDB_BITMAP_UNLOCK               150
#define IDD_DIALOG_FIND                 151
#define IDD_DIALOG_USER                 152
#define IDD_DIALOG_FONTINFO             153
#define XTP_IDR_PREVIEW_TOOLBAR         400
#define XTP_IDD_PREVIEW_TOOLBAR         402
#define IDC_EDIT_DISPTEXT               1000
#define IDC_COMBO_FONTSIZE              1001
#define IDC_CHECK_AUTOUPDATE            1007
#define ID_FILE_VERSION                 1008
#define IDC_STATIC_URL                  1009
#define IDC_STATIC_LICENCE_INFO         1010
#define IDC_EDIT_PROKEY1                1015
#define IDC_EDIT_PROKEY2                1016
#define IDC_EDIT_PROKEY3                1017
#define IDC_EDIT_PROKEY4                1018
#define IDC_EDIT_PROKEY5                1019
#define IDC_BUTTON_ACT1                 1020
#define IDC_BUTTON_ACT2                 1021
#define IDC_BUTTON_ACT3                 1022
#define IDC_STATIC_LIMITDAYS            1024
#define IDC_STATIC_LEAVE1               1025
#define IDC_STATIC_LEAVE2               1026
#define IDC_EDIT_USER_CODE_1            1027
#define IDC_EDIT_USER_CODE_2            1028
#define IDC_EDIT_REG_KEY_1              1029
#define IDC_EDIT_REG_KEY_2              1030
#define IDC_BUTTON_GETWEB               1031
#define IDC_BUTTON_FAX                  1032
#define IDC_STATIC_ACT                  1032
#define IDC_BUTTON_EMAIL                1033
#define IDC_BUTTON_SEARCHPATH           1033
#define IDC_EDIT_FINDPATH               1034
#define IDC_CHECK_EXT1                  1035
#define IDC_CHECK_EXT2                  1036
#define IDC_CHECK_EXT3                  1037
#define IDC_CHECK_EXT4                  1038
#define IDC_CHECK_EXT5                  1039
#define IDC_CHECK_EXT6                  1040
#define IDC_EDIT_EXTETC                 1041
#define IDC_EDIT_COMPANY                1042
#define IDC_EDIT_NAME1                  1043
#define IDC_EDIT_NAME2                  1044
#define IDC_COMBO_SEX                   1045
#define IDC_EDIT_BIRTH1                 1046
#define IDC_EDIT_BIRTH2                 1047
#define IDC_EDIT_BIRTH3                 1048
#define IDC_EDIT_ZIP1                   1049
#define IDC_EDIT_ZIP2                   1050
#define IDC_COMBO_PREF                  1051
#define IDC_EDIT_ADR1                   1052
#define IDC_EDIT_ADR2                   1053
#define IDC_EDIT_ADR3                   1054
#define IDC_EDIT_PHONE1                 1055
#define IDC_EDIT_PHONE2                 1056
#define IDC_EDIT_PHONE3                 1057
#define IDC_EDIT_FAX1                   1058
#define IDC_EDIT_FAX2                   1059
#define IDC_EDIT_FAX3                   1060
#define IDC_EDIT_EMAIL                  1061
#define IDC_COMBO_OCCU                  1062
#define IDC_COMBO_JOB                   1063
#define IDC_COMBO_DM                    1064
#define IDC_BUTTON_REGIST               1065
#define IDC_BUTTON_PRIVACY              1066
#define IDC_EDIT_FONT1                  1066
#define IDC_EDIT_FONT2                  1067
#define IDC_STATIC_KIND                 1068
#define IDC_COMBO1                      1069
#define IDC_COMBO_FAVMAX                1069
#define ID_VIEW_TEXTCTRLBAR             32771
#define ID_VIEW_FONTSELECTBAR           32772
#define ID_VIEW_TABSELECTBAR            32773
#define ID_MENU_COPYFONTFACE            32774
#define ID_MENU_TMPFONT_INSTALL         32775
#define ID_MENU_TMPFONT_UNINSTALL       32776
#define ID_MENU_SEL_LANG_EN             32777
#define ID_MENU_SEL_LANG_JA             32778
#define ID_MENU_SEL_LANG_ALL            32779
#define ID_MENU_SEL_FONT_TMP            32790
#define ID_MENU_SEL_FONT_ORG            32791
#define ID_MENU_SETTING                 32792
#define ID_MENU_UPDATE_CHECK            32793
#define ID_MENU_PLUSS                   32794
#define ID_MENU_SUPPORT                 32795
#define ID_MENU_TMPFONT_FIND            32796
#define ID_MENU_PROPATY                 32799
#define ID_ADD_FAVORITE                 32800
#define ID_ADD_CANDIDATE                32801
#define ID_FAVORITE                     32802
#define ID_CANDIDATE                    32803
#define ID_DEL_FAVORITE                 32804
#define ID_DEL_CANDIDATE                32805
#define ID_NORMAL_LIST                  32806
#define ID_INSTALL_FONT                 32807
#define IDR_TOOLBAR_TAB                 32808
#define ID_32811                        32811
#define ID_MENU_TEST                    32812
#define IDS_DISPTEXT_JA                 61204
#define IDS_DISPTEXT_EN                 61205
#define IDS_AUI_URL                     61206
#define IDS_AUI_VER                     61207
#define IDS_SETTING_DIALOG              61208

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
